data:extend(
{ 	
	--startup settings
	{
		type = "bool-setting",
		name = "disable-vanilla-reactor",
		setting_type = "startup",
		default_value = true,
		order="a1",
		per_user = false,
	},
	{
		type = "string-setting",
		name = "meltdown-mode",
		setting_type = "startup",
		default_value = "meltdown with ruin + sarcophagus",
		allowed_values = {"no meltdown","meltdown without ruin","meltdown with ruin","meltdown with ruin + sarcophagus"},
		order="a2",
		per_user = false,
	},	
    {
		type = "string-setting",
		name = "meltdown-explosion",
		setting_type = "startup",
		default_value = "regular",
		allowed_values = {"regular", "atomic"},
		order="a3",
		per_user = false,
	},		
	{
		type = "string-setting",
		name = "fallout-mode",
		setting_type = "startup",
		default_value = "clouds and radioactivity",
		allowed_values = {"no fallout", "radioactivity","clouds and radioactivity"},
		order="a4",
		per_user = false,
	},
	{
		type = "string-setting",
		name = "fallout-appearance",
		setting_type = "startup",
		default_value = "half-transparent",
		allowed_values = {"invisible", "half-transparent","less transparent","green veil"},
		order="a5",
		per_user = false,
	}, 	
	{
		type = "int-setting",
		name = "clouds_generation",
		setting_type = "startup",
		default_value = 200,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "a6",
		per_user = false,
	},	
	{
		type = "int-setting",
		name = "rr-clouds-duration",
		setting_type = "startup",
		default_value = 80,
		minimum_value = 1,
		maximum_value = 9999999,
		order="a7",
		per_user = false,
	}, 	

	{
		type = "int-setting",
		name = "rr-fallout-duration",
		setting_type = "startup",
		default_value = 600,
		minimum_value = 1,
		maximum_value = 9999999,
		order="a8",
		per_user = false,
	},  		
	{
		type = "int-setting",
		name = "sarcophagus-duration", 
		setting_type = "startup",
		default_value = 1800,
		minimum_value = 1,
		maximum_value = 9999999,
		order="a9",
		per_user = false,
	},	


 	-- runtime settings
    {
		type = "string-setting",
		name = "calculate-stats-function",
		setting_type = "runtime-global",
		default_value = "ownly's formulas",
		allowed_values = {"ownly's formulas", "ingo's formulas"},
		order="b1",
	},	
	{
		type = "bool-setting",
		name = "manually-check-neighbours",
		setting_type = "runtime-global",
		default_value = false,
		order="b2",
	},
	{
		type = "int-setting",
		name = "neighbour-check-delay",
		setting_type = "runtime-global",
		default_value = 600,
		minimum_value = 1,
		order="b3",
	},
	{
		type = "int-setting",
		name = "reactor-scram-duration",
		setting_type = "runtime-global",
		default_value = 180,
		minimum_value = 1,
		order="b4",
	},
	{
		type = "int-setting",
		name = "reactor-starting-duration",
		setting_type = "runtime-global",
		default_value = 30,
		minimum_value = 1,
		order="b5",
	},  
	{
		type = "double-setting",
		name = "rr_energy_consumption_multiplier",
		setting_type = "runtime-global",
		default_value = 1,
		maximum_value = 2.5,
		minimum_value = 0,
		order = "b6",
		per_user = false,
	},	
    {
		type = "bool-setting",
		name = "static-cooling-power-consumption",
		setting_type = "runtime-global",
		default_value = true,
		order="b7",
	},
	{
		type = "string-setting",
		name = "scram-behaviour",
		setting_type = "runtime-global",
		default_value = "limit to current cell",
		--allowed_values = {"stop half-empty", "consume additional cell", "stop abrupt", "free energy in scram"},
		allowed_values = {"limit to current cell", "stop half-empty", "consume additional cell", "decay heat (v1.0.x)"},
		order="b9",
	},
	{
		type = "bool-setting",
		name = "RR-light_fx",
		localised_name = "Light FX",
		localised_description = "Use the new light effects from Mushroom cloud 0.18+",
		setting_type = "startup",
		default_value = false,
		order = "1"
	},
}
)

